freebsd_instance:
  image_family: freebsd-11-3-snap

freebsd_build_task:

  env:
    matrix:
      - package: npm
      - package: npm-node12
      - package: npm-node10

  env:
    matrix:
      - abi: freebsd:11:x86:64
      - abi: freebsd:11:x86:32
        jail_name: j11i386
        exec_prefix: cbsd jexec jname=j11i386

  env:
    GH_API_TOKEN: ENCRYPTED[5e482f417304528148bb96eca8d030eacd6ab9972d482485fc4d42907283b995f658b351e0676e9493a37d815398f541]
A   pkg_latest: pkg -R "${CIRRUS_WORKING_DIR}/.cirrus/pkg/repos"

  prepare_script:
    - $pkg_latest update -f;
    - |
      if test "$abi" = "freebsd:11:x86:32"; then
        $pkg_latest -y cbsd 
        ./scripts/configure_freebsd_ci_jail.sh $jail_name $CIRRUS_WORKING_DIR;
        $exec_prefix $pkg_latest update -f;
      fi
    - $exec_prefix $pkg_latest install -y "${package}" python2 
    - $exec_prefix node --version
    - $exec_prefix npm --version
    - $exec_prefix clang++ --version

  build_script:
    - |
      if test "$abi" = "freebsd:11:x86:32"; then
        changeDir="cd /etc/skel &&"
      fi
      echo "$changeDir npm install --unsafe-perm" | $exec_prefix /bin/sh

  publish_script:
    - |
      if test "$CIRRUS_TAG" != ""; then
        for file in `ls vendor/**/*.node`; do
          parent=${file%/*};
          name=${parent##*/};
          fullyQualifiedName="$(pwd)/$parent/${name}_binding.node";
          mv "$file" "$parent/${name}_binding.node";
          echo -e "New filename\072 $fullyQualifiedName";
          ./scripts/upload-github-release-asset.sh github_api_token=$GH_API_TOKEN owner=sass repo=node-sass tag=$CIRRUS_TAG filename=$fullyQualifiedName;
        done
      fi
