language: node_js

compiler: gcc

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

jobs:
  include:
    - stage: platform-test
      node_js: "14.5"
      os: osx
    - stage: platform-test
      node_js: "12"
      os: osx
    - stage: platform-test
      node_js: "10"
      os: osx

before_install:
  - npm config set python `which python`
  - ${CC:-gcc} --version
  - ${CXX:-g++} --version

install:
  - npm install

script:
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
