language: node_js
node_js:
  - "7"
  - "6"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"

compiler: gcc
sudo: false

os:
  - linux
  - osx

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
    - secure: "iVtYk6Od3tj4xxjX9o0kYb26XyTVriOBK87gSa9i1LMx57v06VI4pK1Ldcq/uhFR9zzYRCEx5GdVuUUyb2eySH+AnWfp4BKNOxLKa0wFFzaMfuSwl2zvoXxJ1KXN8hfL3UjSzXRn1Z1xMbR/2AGQckDHmkMChcWy8d0WtQDMwv8="
    - COVERITY_SCAN_PROJECT_NAME="sass/node-sass"
    - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="XXX"
    - COVERITY_SCAN_BUILD_COMMAND="echo 'already built'"

matrix:
  fast_finish: true
  exclude:
    - node_js: iojs
    - node_js: "0.10"
      os: osx
    - node_js: "0.12"
      os: osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7

before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

script:
  - npm install
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $TRAVIS_NODE_VERSION == "4" ]; then
      npm run lint || exit 1;
    fi
  - npm test

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $TRAVIS_NODE_VERSION == "4" ]; then
      npm run-script coverage;
      curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true ;
    fi

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8dddd234a441d0d07664
    on_success: change
