-
  branches:
    only:
      - release
      - /v\d\.\d\.\d/
    except:
      - master

  os: Visual Studio 2013

  configuration: release

  platform:
    - x64
    - x86

  version: "{build}"

  build: off

  clone_folder: c:\projects\node_modules\node-sass

  # http://www.wintellect.com/devcenter/jrobbins/pdb-files-what-every-developer-must-know
  # http://help.appveyor.com/discussions/kb/32-how-to-build-on-logical-drive-created-by-subst
  init:
    - cmd: >-
        subst s: c:\projects
    - ps: set-location -path s:\node_modules\node-sass
    - ps: Uninstall-Product node 4 $env:platform
    - ps: Write-Host "Installing node-chakracore..." -ForegroundColor Cyan
    - ps: Write-Host "Downloading..."
    - ps: $msiPath = "$env:USERPROFILE\node-chakracore-$env:platform.msi"
    - ps: $file = "https://github.com/nodejs/node-chakracore/releases/download/node-chakracore-7.0.0-pre9/node-chakracore-$($env:platform).msi"
    - ps: (New-Object Net.WebClient).DownloadFile($file, $msiPath)
    - ps: Write-Host "Installing..."
    - ps: cmd /c start /wait msiexec /i $msiPath /quiet
    - ps: Write-Host "node-chakracore installed" -ForegroundColor Green

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      - nodejs_version: 0.10
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 0.12
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 1.0
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 1
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 2
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 3
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 4
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 5
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 6
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - nodejs_version: 7
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - nodejs_version: 8
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - nodejs_version: chakracore
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  install:
    - ps: >-
        if ($env:nodejs_version -eq "chakracore") {
          if ($env:platform -eq "x86") {
            cmd /c C:\"Program Files (x86)\nodejs (chakracore)\nodevars.bat"
            $env:Path = "%APPDATA%\npm;C:\Program Files (x86)\nodejs (chakracore);$($env:Path)"
          } else {
            cmd /c C:\"Program Files\nodejs (chakracore)\nodevars.bat"
            $env:Path = "%APPDATA%\npm;C:\Program Files\nodejs (chakracore);$($env:Path)"
          }
        } else {
          Install-Product node $env:nodejs_version $env:platform
        }
    - node --version
    - npm --version
    - npm install

  test: off

  before_deploy:
    # Save artifacts with full qualified names of binding.node and binding.pdb
    # (which we use in node-sass-binaries repo)
    - ps: >-
        Get-ChildItem .\vendor\**\*.node | % {
           ( $BindingName = $_.FullName ).Split('\\') |
             Select-Object -Last 2 | Select-Object -First 1 } |
               .{ process { (
                  @( $BindingName,
                       ( ( $_, "binding.node" ) -join '_' ) ),
                  @( ".\build\Release\binding.pdb",
                       ( ( $_, "binding.pdb" ) -join '_' ) )
               ) } } | % { Push-AppveyorArtifact $_[0] -FileName $_[1] }

  deploy:
    - provider: GitHub
      description: $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
      artifact:
      auth_token:
        secure: IZIifH990iABY3PQUtkRscTU/NOyYYwptGB6B1y2b618vpphV/2KD/4IWJzSAYAi
      on:
        appveyor_repo_tag: true       # deploy on tag push only

-
  branches:
    except:
      - release
      - /v\d\.\d\.\d/

  skip_branch_with_pr: true
  skip_tags: true

  os: Visual Studio 2013

  configuration: testing

  platform:
    - x86

  version: "{build}"

  build: off

  clone_folder: c:\projects\node_modules\node-sass

  init:
    - cmd: >-
        subst s: c:\projects
    - ps: set-location -path s:\node_modules\node-sass
    - ps: Uninstall-Product node 4 $env:platform
    - ps: Write-Host "Installing node-chakracore..." -ForegroundColor Cyan
    - ps: Write-Host "Downloading..."
    - ps: $msiPath = "$env:USERPROFILE\node-chakracore-$env:platform.msi"
    - ps: $file = "https://github.com/nodejs/node-chakracore/releases/download/node-chakracore-7.0.0-pre9/node-chakracore-$($env:platform).msi"
    - ps: (New-Object Net.WebClient).DownloadFile($file, $msiPath)
    - ps: Write-Host "Installing..."
    - ps: cmd /c start /wait msiexec /i $msiPath /quiet
    - ps: Write-Host "node-chakracore installed" -ForegroundColor Green

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      - nodejs_version: 0.10
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 0.12
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 4
        GYP_MSVS_VERSION: 2013
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - nodejs_version: 6
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - nodejs_version: 7
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - nodejs_version: 8
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - nodejs_version: chakracore
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  install:
    - ps: >-
        if ($env:nodejs_version -eq "chakracore") {
          if ($env:platform -eq "x86") {
            cmd /c C:\"Program Files (x86)\nodejs (chakracore)\nodevars.bat"
            $env:Path = "%APPDATA%\npm;C:\Program Files (x86)\nodejs (chakracore);$($env:Path)"
          } else {
            cmd /c C:\"Program Files\nodejs (chakracore)\nodevars.bat"
            $env:Path = "%APPDATA%\npm;C:\Program Files\nodejs (chakracore);$($env:Path)"
          }
        } else {
          Install-Product node $env:nodejs_version $env:platform
        }
    - node --version
    - node -p process.versions
    - npm --version
    - npm install

  test_script:
    - ps: set-location -path c:\projects\node_modules\node-sass
    - npm test
