version: "{build}"

build: off

environment:
  SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
  matrix:
    # node.js
    - nodejs_version: 0.12.2    # will fetch the latest node.js version

matrix:
  allow_failures:
    - nodejs_version: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install https://github.com/npm/npm.git#6c22e33
  - cd C:\Users\appveyor\AppData\Roaming\npm
  - C:\"Program Files (x86)"\nodejs\npm.cmd install
  - cd C:\projects\node-sass
  - node --version
  - npm --version
  - C:\Users\appveyor\AppData\Roaming\npm\npm.cmd --version
  - git submodule update --init --recursive
  - ps: C:\Users\appveyor\AppData\Roaming\npm\npm.cmd install --msvs_version=2013

test_script: npm test
