resources:
- repo: self

jobs:
- job: linux_amd64_trusty_gcc_openssl
  displayName: 'Linux (amd64; Trusty; GCC; OpenSSL)'
  pool:
    vmImage: 'Ubuntu 16.04'
  container: 10-alpine
  steps:
  - script: apk add --no-cache --virtual .gyp python make g++ && npm install && apk del .gyp
  - template: azure-pipelines/test.yml
