variables:
  node_version:
    node_6_x:
      node_version: 6.x
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x

jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  strategy:
    parallel: 4
    matrix:
      ${{ insert }}: ${{ node_version }}
  steps:
  - task: UsePythonVersion@0
    displayName: Instally Python 2.7 for node-gyp
    inputs:
      versionSpec: '2.7'
  - template: build.yml
  - template: test.yml

- job: Linux
  pool: Hosted Ubuntu 1604
  strategy:
    parallel: 4
    matrix:
      ${{ insert }}: ${{ parameters.node_version }}
  steps:
  - template: build.yml
  - template: test.yml

- job: macOS
  pool:
    vmImage: macOS 10.13
  strategy:
    parallel: 4
    matrix:
      ${{ insert }}: ${{ parameters.node_version }}
  steps:
  - template: build.yml
  - template: test.yml
