name: Build bindings for Alpine releases

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine${{ matrix.alpine }}
      env:
        SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    strategy:
      fail-fast: false
      matrix:
        node:
          - 10
          - 12
          - 14.6
        include:
          - node: 10
            alpine: "3.9"
          - node: 12
            alpine: "3.9"
          - node: 14.6
            alpine: "3.10"
    steps:
      - name: Install Alpine build tools
        run: apk add --no-cache python make git gcc g++

      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install --unsafe-perm

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.node }}
          path: vendor/
