name: Coverage

on:
  push:
    paths:
      - "**/*.js"
      - "test/**"
      - "package.json"
      - "bin/node-sass"
      - ".github/workflows/coverage.yml"
  pull_request:
    paths:
      - "**/*.js"
      - "test/**"
      - "package.json"
      - "bin/node-sass"
      - ".github/workflows/coverage.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install --unsafe-perm

      - name: Run Linting
        run: npm run coverage
