name: Coverage

on:
  push:
    paths:
      - "**/*.js"
      - "test/**"
      - "package.json"
      - "bin/node-sass"
      - ".github/workflows/coverage.yml"
  pull_request:
    paths:
      - "**/*.js"
      - "test/**"
      - "package.json"
      - "bin/node-sass"
      - ".github/workflows/coverage.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install --unsafe-perm

      - name: Run Coverage
        run: npm run coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
