name: Electron Rebuild CI - Linux (x32 & x64)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        electron:
          - 5
          - 6
          - 7
          - 8
        include:
          # includes a new variable for each electron (essentially a switch statement) 
          - electron: 5
            nodeVersion: 70
          - electron: 6
            nodeVersion: 73
          - electron: 7
            nodeVersion: 75
          - electron: 8
            nodeVersion: 76

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        os: ${{ matrix.os }}
    - name: Install packages
      run: npm install --unsafe-perm
    - name: Install electron-rebuild
      run: npm install --save-dev electron-rebuild@latest
    - name: Run on ${{ matrix.os }} - Electron v${{ matrix.electron }} (Node ${{ matrix.nodeVersion }})
      run: ./node_modules/.bin/electron-rebuild -v=${{ matrix.electron }} -w node-sass
    - uses: actions/upload-artifact@v1
      with:
        name: linux_build.zip
        path: build/
    - uses: actions/upload-artifact@v1
      with:
        name: linux_x64_${{ matrix.nodeVersion }}_binding.node
        path: build/release/binding.node
    # npm test failing on pre-existing master issues, commenting out
    #- run: npm test
    #  env:
    #    CI: true
