name: Electron Rebuild CI - OSX (x64)

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        electron:
          - 5
          - 6
          - 7
          - 8
        include:
          # includes a new variable for each electron (essentially a switch statement) 
          - electron: 5
            nodeVersion: 70
          - electron: 6
            nodeVersion: 73
          - electron: 7
            nodeVersion: 75
          - electron: 8
            nodeVersion: 76

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        os: ${{ matrix.os }}
    - name: Node Ver (For debugging)
      run: node -v
    - name: Install packages
      run: npm install --unsafe-perm
    - name: Run on ${{ matrix.os }} - Electron v${{ matrix.electron }} (Node ${{ nodeVersion }})
      run: node ".\node_modules\node-gyp\bin\node-gyp.js" rebuild --target=${{ matrix.electron }}.0.0.0 --arch=x64 --dist-url=https://electronjs.org/headers
    - uses: actions/upload-artifact@v1
      with:
        name: darwin_x64_${{ nodeVersion }}.node
        path: build/release/binding.node
    - uses: actions/upload-artifact@v1
      with:
        name: darwin_x64_${{ nodeVersion }}.pdb
        path: build/release/binding.pdb
    - run: npm test
      env:
        CI: true