name: Electron Rebuild CI - Windows (x32 & x64)

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        electron:
          - 5
          - 6
          - 7
          - 8
        include:
          # includes a new variable for each electron (essentially a switch statement) 
          - electron: 5
            nodeVersion: 70
          - electron: 6
            nodeVersion: 73
          - electron: 7
            nodeVersion: 75
          - electron: 8
            nodeVersion: 76
        arch:
          - ia32
          - x64

    steps:
    - uses: actions/checkout@v2
    - name: Prepare windows environment (preventing errors)
      run: |
        setx PATH "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin;%PATH%"
        set path="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin;%PATH%"
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        os: ${{ matrix.os }}
    - name: Install packages
      run: npm install --unsafe-perm
    - name: Run node-gyp rebuild - Electron v${{ matrix.electron }} (Node ${{ matrix.nodeVersion }})
      run: node ./node_modules/node-gyp/bin/node-gyp.js rebuild --target=${{ matrix.electron }}.0.0 --arch=${{ matrix.arch }} --dist-url=https://electronjs.org/headers
    - uses: actions/upload-artifact@v1
      with:
        name: win32-${{ matrix.arch }}-${{ matrix.nodeVersion }}_binding.node
        path: build/Release/binding.node
    - uses: actions/upload-artifact@v1
      with:
        name: win32-${{ matrix.arch }}-${{ matrix.nodeVersion }}_binding.pdb
        path: build/Release/binding.pdb