name: Electron Rebuild CI - Linux (x32 & x64)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        electron:
          - 5
          - 6
          - 7
          - 8
        include:
          # includes a new variable for each electron (essentially a switch statement) 
          - electron: 5
            nodeVersion: 70
          - electron: 6
            nodeVersion: 73
          - electron: 7
            nodeVersion: 75
          - electron: 8
            nodeVersion: 76

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        os: ${{ matrix.os }}
    - name: Install packages
      run: npm install --unsafe-perm
    - name: Run electron-rebuild - Electron v${{ matrix.electron }} (Node ${{ matrix.nodeVersion }})
      run: npx electron-rebuild -v=${{ matrix.electron }} -w node-sass
    - uses: actions/upload-artifact@v1
      with:
        name: linux-x64-${{ matrix.nodeVersion }}_binding.node
        path: build/Release/binding.node